---
repos:
  - repo: https://github.com/frnmst/md-toc
    rev: 7.0.2
    hooks:
      - id: md-toc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/nbyl/pre-commit-license-checks
    rev: v1.8.0
    hooks:
      - id: license-check-configuration-lint
